name: api-factom-server
version: '0.1.0.0'
category: Web
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
copyright: ! 'Copyright: (c) 2019 Sergey Bushnyak'
license: MIT
github: sigrlami/api-factom
extra-source-files:
- README.md
dependencies:
  - base >=4.7 && <5
  - aeson
  - text
  - time
  - http-conduit
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-auth-swagger
  - servant-options
  - servant-swagger
  - servant-multipart
  - swagger2
  - servant-multipart
  - io-streams
  - optparse-applicative
  - http-conduit
  - postgresql-simple
  - safe
  - jose-jwt
  - cryptonite
  - mtl
  - yaml
  - split
  - uuid
  - wai
  - wai-extra
  - http-types
  - http-api-data
  - http-client-tls
  - network
  - transformers
  - bytestring
  - containers
  - warp
  - json-alt
  #- api-rpc-factom
  - api-factom-types
library:
  source-dirs: src
  exposed-modules:
  - Factom.Rest.Server.Main
  - Factom.Rest.Server.Api
