name: api-factom-server
version: '0.1.0.0'
category: Web
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
copyright: ! 'Copyright: (c) 2019 Sergey Bushnyak'
license: BSD3
github: sigrlami/api-factom
extra-source-files:
- README.md
dependencies:
  - base >=4.7 && <5
  - aeson
  - text
  - time
  - http-conduit
  - servant
  - servant-server
  - servant-client
  - servant-swagger
  - http-client
  - mtl
  - wai
  - wai-extra
  - http-types
  - http-api-data
  - http-client-tls
  - network
  - transformers
  - bytestring
  - containers
  - warp
  - api-factom-types
library:
  source-dirs: src
  exposed-modules:
  - Factom.Rest.Server.API
