# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our custom build tool - Stack
language: generic

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- chmod a+x ~/.local/bin/stack

install:
- stack +RTS -N2 -RTS setup
- stack --no-terminal --install-ghc test --only-dependencies

script:
#- stack --no-terminal test --haddock --no-haddock-deps

cache:
  directories:
  - $HOME/.stack
