name: api-factom-client
version: '0.1.0.0'
category: Web
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
copyright: ! 'Copyright: (c) 2019 Sergey Bushnyak'
license: MIT
github: kompendium-llc/api-factom
extra-source-files:
- README.md
dependencies:
  - base >=4.7 && <5
  - aeson
  - text
  - time
  - http-conduit
  - servant
  - servant-client
  - servant-elm
  - http-client
  - http-client-tls
  - network
  - transformers
  - bytestring
  - containers
  - json-alt
  - elm-export

library:
  source-dirs: src
  exposed-modules:
  - Factom.Rest.Client.Api
  - Factom.Rest.Client.Types
  - Factom.Rest.Client.Utils
  - Factom.Rest.Client.Types.User
  - Factom.Rest.Client.Types.Chain
  - Factom.Rest.Client.Types.Entry
executables:
  factom-oapi-app:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - http-conduit
    - http-client
    - aeson
    - stm
    - text
    - time
    - api-factom-client
    - servant-elm
    - elm-export
